name: jg_music
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  audio_service: ^0.18.15
  flutter:
    sdk: flutter
  http: ^1.2.2
  just_audio: ^0.9.41
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  youtube_explode_dart: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
